source/percona-release.rst
Modified percona-release
modified for apt repos - /percona-original-release.list
=> PREL-49 Update repo information

source/percona-release.rst
Used OS names in titles
Moved errors and their fix to the bottom of the section
=> PREL-118 Doc: Reworked install instructions

source/percona-release.rst
Changes to be committed:
modified:   source/percona-release.rst
=> PREL-133 Fix example

source/.res/mongodb-repos.txt, source/.res/mysql-repos.txt, source/.res/postgresql-repos.txt, source/percona-release.rst
modified:   source/.res/mongodb-repos.txt
modified:   source/.res/mysql-repos.txt
modified:   source/.res/postgresql-repos.txt
modified:   source/percona-release.rst
=> PREL-137 Updated repo lists with new distribution repos

.gitignore, source/.res/mysql-repos.txt, source/percona-release.rst
modified:   .gitignore
modified:   source/.res/mysql-repos.txt
modified:   source/percona-release.rst
=> PREL-141 Added PDPS 8.0.25 to products and repo lists

docs/index.md, docs/installation-and-update.md, docs/installing.md, docs/percona-release.md, docs/repository-location.md, docs/updating.md, docs/usage.md, mkdocs-netlify.yml, mkdocs.yml
modified:   docs/index.md
new file:   docs/installation-and-update.md
new file:   docs/installing.md
new file:   docs/repository-location.md
new file:   docs/updating.md
modified:   mkdocs-netlify.yml
=> PREL-152 Split docs into topics

docs/percona-release.md, docs/repository-location.md
=> PREL-160 Doc: Add PSMDB 5.0 and PDMDB 4.4.8 to repo and product list

docs/installing.md
modified:   docs/installing.md
=> PREL-164 Fix  link to the section within install page

docs/percona-release.md, docs/repository-location.md
=> PREl-171 Added PDMDB 4.4.10 to repo and product lists

docs/percona-release.md, docs/repository-location.md
=> PREL-176 Added PPG 12.9 to repo list

docs/percona-release.md, docs/repository-location.md
=> PREL-179-Added PDMDb 5.0 to repo and product list

docs/installing.md
modified:   docs/installing.md
=> ENG-19 Added install instructions from the website

docs/percona-release.md, docs/repository-location.md
=> PREL-183 Added PDMDB 4.2.18 to repo list

docs/percona-release.md, docs/repository-location.md
Added pdmdb 4.4.12, 5.0.6, PDPS 8.0.27, PDPXC 8.0.25, 8.0.26
=> PREL-184 Updated repo and product lists:

_resource/overrides/main.html, _resource/overrides/partials/header.html, mkdocs-netlify.yml
modified:   mkdocs-netlify.yml
new directory: _resource/overrides/
=> PREL-185 Customise doc layout for migration to new hosting platform

docs/percona-release.md, docs/repository-location.md
Added PDMDB4.4.13, PPG 13.6, 14.2
=> PREL-186 Updated repo and product lists:

_resource/overrides/404.html, docs/percona-release.md, docs/repository-location.md, mkdocs-percona.yml, mkdocs.yml
Updated repo and product lists with PDMDB 5.0.7
Got rid of netlify in config names
new file:   _resource/overrides/404.html
renamed:    mkdocs-netlify.yml -> mkdocs-percona.yml
=> PREl-193 Added 404 page

docs/installing.md
"See also" was misspelled. Fix it and label it as an admonition.
=> Fix typos in admonitions

docs/repository-location.md
=> PREL-196 Added new PG versions to repo list

README.md, _resource/overrides/main.html, docs/copyright.md, docs/index.md, docs/installation-and-update.md, docs/installing.md, docs/percona-release.md, docs/updating.md
Updated and improved installation instructions
* Improved `README.md`
* Improved index page (more content, re-ordered paragraphs)
* Simplified installation instructions
* Removed redundant installation instructions
* Removed redundant repository information
* Simplified Copyright and Licensing page, updated copyright date
* Fixed URLs in the `main.html` HTML template
* Minor cleanups
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>
=> Updated and improved installation instructions

docs/percona-release.md, docs/repository-location.md
PDPXC 8.0.28
PDMDB 4.4.15
Fixed command syntax in examples
=> PREL-200 Added new SW versions to repo lists:

docs/repository-location.md
=> PREL-201 Added new repos

docs/repository-location.md
Added PDMDB 4.2, 4.4, 5.0
New PG versions
=> PREL-205 Updated repo list

CONTRIBUTING.md
=> PREL-206 Contributing guide

docs/repository-location.md
=> PREL-207 Updated the repo lists

docs/repository-location.md
=> PREL-219 Updated PDMDB versions in list

docs/repository-location.md
=> PREL-221 Updated PDPS and PDPXC versions in list

docs/mongodb.md, docs/postgresql.md
Added PG 15.2, 14.7, 13.10, 12.14, 11.19
Added PDMDB 6.0.5, 5.0.15, 4.4.19, 4.2.24
=> PREL-226 updated repo list

docs/mysql.md
=> PREL-227 Update the MySQL software repositories list

_resource/overrides/main.html
modified:   _resource/overrides/main.html
=> PREL-228 Updated Google tag Manager for the docs

_resource/overrides/main.html, mkdocs.yml, requirements.txt
modified:   _resource/overrides/main.html
modified:   requirements.txt
=> Add text snippets to link previews

docs/mongodb.md, docs/percona-release.md, docs/repository-location.md
=> PREL-231 Added new PDMDB repos to the list

docs/copyright.md, docs/trademark-policy.md, mkdocs.yml
modified:   docs/copyright.md
modified:   docs/trademark-policy.md
=> DOCS-72 Update Trademark Policy, Copyright and Licensing Information

docs/postgresql.md
modified:   docs/postgresql.md
=> PREL-234 Added minor PPG versions to repo list

docs/installing.md
modified:   docs/installing.md
=> HD-21078 Updated the URLs for installation instructions for products

docs/mongodb.md
=> PREL-238 Added new versions of PDMDB to repo list

docs/postgresql.md
modified:   docs/postgresql.md
=> PREL-239 Added new versions of PostgtreSQL distro to repo list

docs/mysql.md
=> PREL-241 Add PDPS 8.0.34 and PDPXC 8.0.33 to the list of distributions

docs/mongodb.md
=> PREL-244 Added PSMDB 7.0 to repo list

mkdocs.yml
modified:   mkdocs-percona.yml
=> Fix the code copy button

docs/mongodb.md
=> PREL-245 Updated repo list with new PDMDB versions

docs/mysql.md
=> PREL-247 Add pxb 8.1 major version

docs/mysql.md
=> PREL-254 Add PS and PDPS 8.1 versions

docs/mysql.md
=> PREL-255 Add PXB 8.2 version

docs/mongodb.md, docs/postgresql.md, mkdocs.yml
modified:   docs/mongodb.md
modified:   docs/postgresql.md
=> PREL-257 Added new PG repos and PDMDB 7.0 to repo list

docs/mirror.md, mkdocs.yml
=> DOCS-4 Mirrors

docs/mongodb.md, mkdocs.yml
=> PREL-262 Added new versions of PDMDB to repo list

docs/mysql.md
=> PREL-263 Add new versions of PS, PXB, PDPS and PDPXC to repo list

docs/postgresql.md
modified:   docs/postgresql.md
=> PREL-238 Added new versions of PostgreSQL to repo list

_resource/overrides/partials/header.html
=> DOCS-125 Reword Return link to Percona <technology> documentation

_resource/overrides/partials/header.html
=> Update the link to the homepage
